[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
tokio = { version = "1", features = ["full"] }
rodio = "0.20.1"
mp3-duration = "0.1.10"
walkdir = "2"
dirs = "4.0"
rand = "0.8"
