[colors]
background = #00000000
backgroundtop = #99000000
foreground = #FFFFFF
primary = #399A9C
alert = #A54242
disabled = #C5C8C6
blue= #0082FC
white= #FFFFFF
grey = #36454F
red = #FF0000
active = #1FFFFFFF
inactive = #4DC5C8C6
inactivebg = #70000000

[bar/top]
monitor = ${env:MONITOR}
top = true
width = 100%
height = 20pt

background = ${colors.backgroundtop}
foreground = ${colors.foreground}

line-size = 3pt

font-0 = "Hack Nerd Font Mono:size=14;4"
font-1 = "Hack Nerd Font Mono:size=25;3"
font-2 = "Hack Nerd Font Mono:size=20;4"
font-3 = "Hack Nerd Font Mono:size=7;1"

modules-left = i3 virtualdesktop
modules-right = shutdown sleep hibernate restart memory cpu

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

[bar/bottom]
monitor = ${env:MONITOR}
bottom = true
width = 100%
height = 35pt

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

font-0 = "Hack Nerd Font Mono:size=10;0"
font-1 = "Hack Nerd Font Mono:size=50;12"
font-2 = "Hack Nerd Font Mono:size=30;7.5"
font-3 = "Hack Nerd Font Mono:size=20;5"
font-4 = "Hack Nerd Font Mono:size=15;3"
font-5 = "Hack Nerd Font Mono:size=36;9"
font-6 = "Font Awesome 6 Pro Solid:size=20;5"

modules-left = terminal filemanager spectacle browser code 
modules-right = pulseaudio xkeyboard battery wlan eth bluetooth date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

# Modules
[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/i3]
type = internal/i3
index-sort = true

format = <label-state>

label-focused = %index%
label-focused-foreground = ${colors.white}
label-focused-background = ${colors.active}
label-focused-underline = ${colors.primary}
label-focused-padding = 2

label-unfocused = %index%
label-unfocused-background = ${colors.inactivebg}
label-unfocused-underline = ${colors.inactive}
label-unfocused-padding = 2

label-visible = %index%
label-visible-background = ${colors.inactivebg}
label-visible-underline = ${colors.inactive}
label-visible-padding = 2

label-urgent = %index%
label-urgent-background = ${colors.inactivebg}
label-urgent-underline = ${colors.inactive}
label-urgent-padding = 2

label-separator = "%{T4} %{T1}"
label-separator-padding = 0

[module/shutdown]
type = custom/script
exec = echo " %{T3}󰐥%{T1} "
click-left = poweroff

[module/sleep]
type = custom/script
exec = echo " %{T3}󰤄%{T1} "
click-left = systemctl suspend

[module/hibernate]
type = custom/script
exec = echo " %{T3}%{T1} "
click-left = systemctl hybrid-sleep

[module/restart]
type = custom/script
exec = echo " %{T3}󰜉%{T1}  "
click-left = reboot

[module/virtualdesktop]
type = custom/script
exec = echo "%{T4} %{B#70000000}    %{T2}󰙟%{T4}    %{T1}"
click-left = /home/yuqingliu/.config/polybar/workspace_adder.sh &

[module/terminal]
type = custom/script
exec = xdotool search --onlyvisible --classname alacritty > /dev/null 2>&1 && echo "%{B#3FFFFFFF}%{u#39949C}%{+u}  %{T3}%{T1}  %{-u}%{B-} " || echo "%{B#0FFFFFFF}%{u#373B41}%{+u}  %{T3}%{T1}  %{-u}%{B-} "
interval = 1
click-left = alacritty &

[module/filemanager]
type = custom/script
exec = ps -ef | grep -v grep | grep alacritty | grep -q ranger && echo "%{B#3FFFFFFF}%{u#39949C}%{+u}  %{T3}%{T1}  %{-u}%{B-} " || echo "%{B#0FFFFFFF}%{u#373B41}%{+u}  %{T3}%{T1}  %{-u}%{B-} "
interval = 1
click-left = alacritty -e bash -c 'source ranger; exec bash' &

[module/spectacle]
type = custom/script
exec = xdotool search --onlyvisible --classname ksnip > /dev/null 2>&1 && echo "%{B#3FFFFFFF}%{u#39949C}%{+u}  %{T3}%{T1}  %{-u}%{B-} " || echo "%{B#0FFFFFFF}%{u#373B41}%{+u}  %{T3}%{T1}  %{-u}%{B-} "
interval = 1
click-left = ksnip &

[module/browser]
type = custom/script
exec = xdotool search --onlyvisible --classname edge > /dev/null 2>&1 && echo "%{B#3FFFFFFF}%{u#39949C}%{+u}  %{T3}󰇩%{T1}  %{-u}%{B-} " || echo "%{B#0FFFFFFF}%{u#373B41}%{+u}  %{T3}󰇩%{T1}  %{-u}%{B-} "
interval = 1
click-left = microsoft-edge-stable &

[module/code]
type = custom/script
exec = xdotool search --onlyvisible --classname code > /dev/null 2>&1 && echo "%{B#3FFFFFFF}%{u#39949C}%{+u}  %{T3}󰨞%{T1}  %{-u}%{B-} " || echo "%{B#0FFFFFFF}%{u#373B41}%{+u}  %{T3}󰨞%{T1}  %{-u}%{B-} "
label-active-background = ${colors.background-alt}
click-left = code &

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = " %{T3}󰕾%{T-}"
format-volume-prefix-foreground = ${colors.primary}

format-volume = <label-volume> <ramp-volume> 

label-volume = " %{T7}%{T-}  "
label-volume-foreground = ${colors.grey}

ramp-volume-0 = " %{O-63}%{T7}%{F#36454F}%{T-}%{F-}   "
ramp-volume-1 = " %{O-63}%{T7}%{T-}   "
ramp-volume-2 = " %{O-63}%{T7}%{T-}   "
ramp-volume-3 = " %{O-63}%{T7}%{T-}   "
ramp-volume-4 = " %{O-63}%{T7}%{T-}   "
ramp-volume-5 = " %{O-63}%{T7}%{T-}   "

label-muted = " %{T3}󰖁 "
label-muted-foreground = ${colors.disabled}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format = <label-indicator> <label-layout>

format-prefix = "%{T6}%{T1} %{T4}"
format-prefix-foreground = ${colors.primary} 
format-prefix-background = ${colors.background} 

label-layout = "%layout% "

[module/battery]
type = internal/battery
full-at = 95

format-charging = <ramp-capacity>
format-discharging = <ramp-capacity>
format-full = " %{T7}%{F-} "

ramp-capacity-0 = " %{T7}%{F-} "
ramp-capacity-1 = " %{T7}%{F-} "
ramp-capacity-2 = " %{T7}%{F-} "
ramp-capacity-3 = " %{T7}%{F-} "
ramp-capacity-4 = " %{T7}%{F-} "

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
format-prefix-foreground = ${colors.primary}
label = "%percentage_used:2%% "

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}
label = "%percentage:2%% "

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected> <ramp-signal>
format-disconnected = <label-disconnected>

[module/wlan]
inherit = network-base
interface-type = wireless

label-connected = "  %{A1:alacritty -e nmtui &:}%{T7}%{A}"
label-connected-foreground = ${colors.grey}

ramp-signal-0 = "%{O-43}%{T7}"
ramp-signal-1 = "%{O-43}%{T7}"
ramp-signal-2 = "%{O-43}%{T7}"
ramp-signal-3 = "%{O-43}%{T7}"
ramp-signal-4 = "%{O-43}%{T7}"
ramp-signal-5 = "%{O-43}%{T7}"
ramp-signal-6 = "%{O-43}%{T7}"
ramp-signal-7 = "%{O-43}%{T7}"

label-disconnected = "%{A1:alacritty -e nmtui &:}  %{T3}%{A}"
label-disconnected-foreground = ${colors.red}

[module/eth]
inherit = network-base
interface-type = wired

label-connected = "%{A1:alacritty -e nmtui &:}  %{T3}󰩩%{A} "

label-disconnected = "%{A1:alacritty -e nmtui &:}  %{T3}󱖣%{A} "
label-disconnected-foreground = ${colors.red}

[module/bluetooth]
type = custom/text
label = "   %{T3}󰂰%{T1}   "
label-foreground = ${colors.blue}
click-left = blueberry &

[module/date]
type = internal/date
interval = 1

date = "%{T5}%a, %b %d, %Y %I:%M %p  "

label = %date%
label-foreground = ${colors.primary}

[settings]
screenchange-reload = true
pseudo-transparency = false

; vim:ft=dosini
